### ISSUE TITLE
Demultiplexing Pseudocode Feedback

### ISSUE THREAD

**Issue by julhays** [graceHach/Demultiplex#1]
Hi Grace,

Your logic is easy to follow and your algorithm makes sense. I like the dictionary system you described to keep track of the statistics for the number of read-pairs for each index pair. I believe your algorithm meets all the requirements outlined in the assignment description. I'm a little confused about the purpose of having a dictionary that holds the status of if a file is open of not - I think you could append each new entry onto the file after each iteration of the loop but maybe I am missing something. One thing that you could do to improve and simplify your algorithm is separate some of the aspects of this code into functions, such as computing the reverse compliment or creating the new header, but this is not entirely necessary. It's also redundant to have a check for both if N is in the index and if the index is in the valid set of 24 because if the index does contain an N it won't be in the set of 24. Overall, this seems like a solid plan and I hope coding this up goes smoothly!

-Jules

**Comment by graceHach** [comment]
Hey Jules,

Thanks for the feedback! The purpose of the dictionary is just to keep track of the file handles for writing. That way, if a filename isn't in the dictionary, I can open it, clear its current content (this can be helpful to avoid doubling up the output files if the code is re-run), and generate a file handle to append to it when needed. When the code is done, the dictionary is used to systematically close all the files. That way, I'm not opening and closing the file more times than necessary, or writing to the file from multiple redundant streams. I will also definitely add functions lol.
Good point about the Ns, I totally missed that!

Thanks again,
Grace
