### ISSUE TITLE
Feedback for Demultiplex pseudocode 

### ISSUE THREAD

**Issue by Mahmoud-56** [graceHach/Demultiplex#2]
Hi Grace. I think you have done a really good job so far, your pseudocode addresses all the questions in the assignment. It is readable and easy to follow. I liked how you are counting the number of matched reads in a dictionary, something I forgot to incorporate in my code. I think you do not need to check for Ns if you know that the index is in the list of indexes. Also, If you are writing R1 and R2 for both unknown and unmatched to the "undetermined file", how are you using the file handles in the dictionary to separate them into their respective files? I'm just making sure I understand what you are trying to do here. That's all I have. Best of luck!

**Comment by graceHach** [comment]
You're pretty much spot on! The unknown files and hopped files and file handles are separate from the dictionary of matched reads. I was thinking of adding them to the dict with the key 'unk_R1' or 'hopped_R1' for symmetry, I'll probably do that for readability's sake.

Thanks for the feedback, I can tell you went into this in great detail!
