### ISSUE TITLE
Demultiplexing - Pseudocode Feedback 

### ISSUE THREAD

**Issue by klai22** [graceHach/Demultiplex#3]
Hi Grace! 

Great job on your pseudocode, it is very detailed! I especially like how you made it clear to follow with the indentations. 

I wonder if you still need to check for Ns in the indices if your index was already matched to one in the known indexes file. Although, I’m sure the extra step doesn’t hurt, it may make your code less efficient. 

It also would have been a little easier for me to follow your pseudocode if you had clearly distinguished when you set variables vs when they are part of words in your explanations, but that is a very minor detail. 

I had trouble finding where your high-level functions were, but that may have just been an issue on my side. I wonder if your pseudocode would have benefited from references to high level functions you plan to use. However, that may also overcomplicate it if so. Definitely something to think about. 

Overall great job! I must say I had trouble picking out areas of improvement here. 

Best, 
Kenneth Lai

**Comment by graceHach** [comment]
Hey Kenny,

Thanks for the feedback! I didn't define any functions yet, I didn't realize that was supposed to be a part of the pseudocode! You're absolutely right though, it's a good idea to define functions early on so they don't end up being too complex. You make an excellent point about variables vs words, the next time I write pseudocode I'm going to put all variable names in all caps or something so they're easier to pick out. 

Thanks for the feedback,
Grace
